/**
 * The EU's 27 member states, each with its first-level administrative
 * subdivisions, for the personal calculator's two-step "where are you
 * shipping from" fields: a country dropdown, then a state dropdown
 * populated from the chosen country. Both are real `<select>` lists, not
 * free text — see PersonalCalculator.tsx.
 *
 * Country display names are localized (looked up per-locale from
 * `dictionary.personalCalculator.euCountryNames[id]`, the same split
 * every other reference list in this codebase uses — see CARGO_CATEGORIES
 * / DESTINATIONS in pricing.ts). State names are deliberately NOT
 * localized: the ~430 entries below, translated into English, German and
 * Arabic, would be a lot of unreviewable translation for data that (a)
 * mostly doesn't change any price and (b) most customers will recognize
 * in the spelling below regardless of the site's UI language, the same
 * way an international form usually shows region names in one canonical
 * spelling. Flagged here as a deliberate scope call, not an oversight —
 * worth reconsidering if it turns out to read wrong for Arabic-speaking
 * senders in particular.
 *
 * Only Germany's id and its states are ever read by the pricing model
 * (see deriveShippingZone / isBerlinBrandenburgState in pricing.ts) —
 * every other country prices as the same `eu-dhl` zone regardless of
 * which one it is or which state is picked. The other 26 countries' state
 * lists exist purely so the dropdown is real and complete, not because
 * anything downstream calculates from them.
 *
 * Sourced from each country's real first-level administrative divisions
 * (states/regions/counties/provinces — terminology genuinely varies by
 * country), not a statistical construct like Eurostat's NUTS regions,
 * which for most countries don't correspond to anything a resident would
 * recognize as "their state." Three countries (Cyprus, Luxembourg, Malta)
 * are small enough, and in Cyprus's case politically split enough, that a
 * single self-named entry stands in for a formal subdivision list — this
 * is the "governorates, in case it has no states" case.
 */
export interface EuCountry {
  id: string;
  states: string[];
}

export const EU_COUNTRIES: EuCountry[] = [
  {
    id: "AT",
    states: [
      "Burgenland",
      "Carinthia",
      "Lower Austria",
      "Upper Austria",
      "Salzburg",
      "Styria",
      "Tyrol",
      "Vorarlberg",
      "Vienna",
    ],
  },
  {
    id: "BE",
    states: ["Flemish Region", "Walloon Region", "Brussels-Capital Region"],
  },
  {
    id: "BG",
    states: [
      "Blagoevgrad",
      "Burgas",
      "Dobrich",
      "Gabrovo",
      "Haskovo",
      "Kardzhali",
      "Kyustendil",
      "Lovech",
      "Montana",
      "Pazardzhik",
      "Pernik",
      "Pleven",
      "Plovdiv",
      "Razgrad",
      "Ruse",
      "Shumen",
      "Silistra",
      "Sliven",
      "Smolyan",
      "Sofia City",
      "Sofia Province",
      "Stara Zagora",
      "Targovishte",
      "Varna",
      "Veliko Tarnovo",
      "Vidin",
      "Vratsa",
      "Yambol",
    ],
  },
  {
    id: "HR",
    states: [
      "Bjelovar-Bilogora",
      "Brod-Posavina",
      "Dubrovnik-Neretva",
      "Istria",
      "Karlovac",
      "Koprivnica-Križevci",
      "Krapina-Zagorje",
      "Lika-Senj",
      "Međimurje",
      "Osijek-Baranja",
      "Požega-Slavonia",
      "Primorje-Gorski Kotar",
      "Šibenik-Knin",
      "Sisak-Moslavina",
      "Split-Dalmatia",
      "Varaždin",
      "Virovitica-Podravina",
      "Vukovar-Srijem",
      "Zadar",
      "Zagreb County",
      "City of Zagreb",
    ],
  },
  { id: "CY", states: ["Cyprus"] },
  {
    id: "CZ",
    states: [
      "Prague",
      "Central Bohemian",
      "South Bohemian",
      "Plzeň",
      "Karlovy Vary",
      "Ústí nad Labem",
      "Liberec",
      "Hradec Králové",
      "Pardubice",
      "Vysočina",
      "South Moravian",
      "Olomouc",
      "Zlín",
      "Moravian-Silesian",
    ],
  },
  {
    id: "DK",
    states: [
      "Capital Region",
      "Zealand",
      "Southern Denmark",
      "Central Denmark",
      "North Denmark",
    ],
  },
  {
    id: "EE",
    states: [
      "Harju",
      "Hiiu",
      "Ida-Viru",
      "Jõgeva",
      "Järva",
      "Lääne",
      "Lääne-Viru",
      "Põlva",
      "Pärnu",
      "Rapla",
      "Saare",
      "Tartu",
      "Valga",
      "Viljandi",
      "Võru",
    ],
  },
  {
    id: "FI",
    states: [
      "Uusimaa",
      "Southwest Finland",
      "Satakunta",
      "Kanta-Häme",
      "Pirkanmaa",
      "Päijät-Häme",
      "Kymenlaakso",
      "South Karelia",
      "South Savo",
      "North Savo",
      "North Karelia",
      "Central Finland",
      "South Ostrobothnia",
      "Ostrobothnia",
      "Central Ostrobothnia",
      "North Ostrobothnia",
      "Kainuu",
      "Lapland",
      "Åland",
    ],
  },
  {
    id: "FR",
    states: [
      "Auvergne-Rhône-Alpes",
      "Bourgogne-Franche-Comté",
      "Brittany",
      "Centre-Val de Loire",
      "Corsica",
      "Grand Est",
      "Hauts-de-France",
      "Île-de-France",
      "Normandy",
      "Nouvelle-Aquitaine",
      "Occitanie",
      "Pays de la Loire",
      "Provence-Alpes-Côte d'Azur",
    ],
  },
  {
    id: "DE",
    states: [
      "Baden-Württemberg",
      "Bavaria",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hesse",
      "Lower Saxony",
      "Mecklenburg-Vorpommern",
      "North Rhine-Westphalia",
      "Rhineland-Palatinate",
      "Saarland",
      "Saxony",
      "Saxony-Anhalt",
      "Schleswig-Holstein",
      "Thuringia",
    ],
  },
  {
    id: "GR",
    states: [
      "Attica",
      "Central Greece",
      "Central Macedonia",
      "Crete",
      "Eastern Macedonia and Thrace",
      "Epirus",
      "Ionian Islands",
      "North Aegean",
      "Peloponnese",
      "South Aegean",
      "Thessaly",
      "Western Greece",
      "Western Macedonia",
    ],
  },
  {
    id: "HU",
    states: [
      "Bács-Kiskun",
      "Baranya",
      "Békés",
      "Borsod-Abaúj-Zemplén",
      "Budapest",
      "Csongrád-Csanád",
      "Fejér",
      "Győr-Moson-Sopron",
      "Hajdú-Bihar",
      "Heves",
      "Jász-Nagykun-Szolnok",
      "Komárom-Esztergom",
      "Nógrád",
      "Pest",
      "Somogy",
      "Szabolcs-Szatmár-Bereg",
      "Tolna",
      "Vas",
      "Veszprém",
      "Zala",
    ],
  },
  {
    id: "IE",
    states: [
      "Carlow",
      "Cavan",
      "Clare",
      "Cork",
      "Donegal",
      "Dublin",
      "Galway",
      "Kerry",
      "Kildare",
      "Kilkenny",
      "Laois",
      "Leitrim",
      "Limerick",
      "Longford",
      "Louth",
      "Mayo",
      "Meath",
      "Monaghan",
      "Offaly",
      "Roscommon",
      "Sligo",
      "Tipperary",
      "Waterford",
      "Westmeath",
      "Wexford",
      "Wicklow",
    ],
  },
  {
    id: "IT",
    states: [
      "Abruzzo",
      "Basilicata",
      "Calabria",
      "Campania",
      "Emilia-Romagna",
      "Friuli-Venezia Giulia",
      "Lazio",
      "Liguria",
      "Lombardy",
      "Marche",
      "Molise",
      "Piedmont",
      "Puglia",
      "Sardinia",
      "Sicily",
      "Tuscany",
      "Trentino-Alto Adige",
      "Umbria",
      "Aosta Valley",
      "Veneto",
    ],
  },
  {
    id: "LV",
    states: [
      "Kurzeme",
      "Latgale",
      "Riga",
      "Vidzeme",
      "Zemgale",
    ],
  },
  {
    id: "LT",
    states: [
      "Alytus",
      "Kaunas",
      "Klaipėda",
      "Marijampolė",
      "Panevėžys",
      "Šiauliai",
      "Tauragė",
      "Telšiai",
      "Utena",
      "Vilnius",
    ],
  },
  { id: "LU", states: ["Luxembourg"] },
  { id: "MT", states: ["Malta"] },
  {
    id: "NL",
    states: [
      "Drenthe",
      "Flevoland",
      "Friesland",
      "Gelderland",
      "Groningen",
      "Limburg",
      "North Brabant",
      "North Holland",
      "Overijssel",
      "Utrecht",
      "Zeeland",
      "South Holland",
    ],
  },
  {
    id: "PL",
    states: [
      "Lower Silesian",
      "Kuyavian-Pomeranian",
      "Lublin",
      "Lubusz",
      "Łódź",
      "Lesser Poland",
      "Masovian",
      "Opole",
      "Subcarpathian",
      "Podlaskie",
      "Pomeranian",
      "Silesian",
      "Świętokrzyskie",
      "Warmian-Masurian",
      "Greater Poland",
      "West Pomeranian",
    ],
  },
  {
    id: "PT",
    states: [
      "Aveiro",
      "Beja",
      "Braga",
      "Bragança",
      "Castelo Branco",
      "Coimbra",
      "Évora",
      "Faro",
      "Guarda",
      "Leiria",
      "Lisbon",
      "Portalegre",
      "Porto",
      "Santarém",
      "Setúbal",
      "Viana do Castelo",
      "Vila Real",
      "Viseu",
      "Azores",
      "Madeira",
    ],
  },
  {
    id: "RO",
    states: [
      "Alba",
      "Arad",
      "Argeș",
      "Bacău",
      "Bihor",
      "Bistrița-Năsăud",
      "Botoșani",
      "Brașov",
      "Brăila",
      "Bucharest",
      "Buzău",
      "Caraș-Severin",
      "Călărași",
      "Cluj",
      "Constanța",
      "Covasna",
      "Dâmbovița",
      "Dolj",
      "Galați",
      "Giurgiu",
      "Gorj",
      "Harghita",
      "Hunedoara",
      "Ialomița",
      "Iași",
      "Ilfov",
      "Maramureș",
      "Mehedinți",
      "Mureș",
      "Neamț",
      "Olt",
      "Prahova",
      "Satu Mare",
      "Sălaj",
      "Sibiu",
      "Suceava",
      "Teleorman",
      "Timiș",
      "Tulcea",
      "Vaslui",
      "Vâlcea",
      "Vrancea",
    ],
  },
  {
    id: "SK",
    states: [
      "Bratislava",
      "Trnava",
      "Trenčín",
      "Nitra",
      "Žilina",
      "Banská Bystrica",
      "Prešov",
      "Košice",
    ],
  },
  {
    id: "SI",
    states: [
      "Mura",
      "Drava",
      "Carinthia",
      "Savinja",
      "Central Sava",
      "Lower Sava",
      "Southeast Slovenia",
      "Littoral–Inner Carniola",
      "Central Slovenia",
      "Upper Carniola",
      "Gorizia",
      "Coastal–Karst",
    ],
  },
  {
    id: "ES",
    states: [
      "Andalusia",
      "Aragon",
      "Asturias",
      "Balearic Islands",
      "Canary Islands",
      "Cantabria",
      "Castile-La Mancha",
      "Castile and León",
      "Catalonia",
      "Extremadura",
      "Galicia",
      "La Rioja",
      "Madrid",
      "Murcia",
      "Navarre",
      "Basque Country",
      "Valencia",
    ],
  },
  {
    id: "SE",
    states: [
      "Stockholm",
      "Uppsala",
      "Södermanland",
      "Östergötland",
      "Jönköping",
      "Kronoberg",
      "Kalmar",
      "Gotland",
      "Blekinge",
      "Skåne",
      "Halland",
      "Västra Götaland",
      "Värmland",
      "Örebro",
      "Västmanland",
      "Dalarna",
      "Gävleborg",
      "Västernorrland",
      "Jämtland",
      "Västerbotten",
      "Norrbotten",
    ],
  },
];

export const GERMANY_COUNTRY_ID = "DE";

export const getEuCountry = (id: string) =>
  EU_COUNTRIES.find((c) => c.id === id);
